//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cells.tommydurant2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int ImgId { get; set; }
        public byte[] ImgBin { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> H { get; set; }
        public string LABEL { get; set; }
        public string ANNOTATOR { get; set; }
    }
}
